apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.username }}/helep-user-service:{{ .Values.global.image.tag }}
        ports:
        - containerPort: 8001
        env:
        - name: KAFKA_BOOTSTRAP
          value: {{ .Values.global.kafka.bootstrap }}
        - name: DB_PATH
          value: /data/user.db
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: helep-secret
              key: JWT_SECRET
        - name: SERVICE_PORT
          value: "8001"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: user-data
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: user-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
