pipeline {
    agent any

    environment {
        DOCKER_USER = 'carlos15976'
        IMAGE_TAG   = '0.1.0'
    }

    stages {
        stage('Lint Helm') {
            steps {
                sh 'helm lint charts/helep'
            }
        }

        stage('Build Images') {
            steps {
                script {
                    ['user-service','sos-service','dispatch-service',
                     'notification-service','analytics-service'].each { svc ->
                        sh "docker build -t \/helep-\:\ services/\"
                    }
                }
            }
        }

        stage('Scan Images') {
            steps {
                script {
                    ['user-service','sos-service','dispatch-service',
                     'notification-service','analytics-service'].each { svc ->
                        sh "trivy image --severity HIGH,CRITICAL --exit-code 1 \/helep-\:\"
                    }
                }
            }
        }

        stage('Push Images') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo \ | docker login -u \ --password-stdin'
                    script {
                        ['user-service','sos-service','dispatch-service',
                         'notification-service','analytics-service'].each { svc ->
                            sh "docker push \/helep-\:\"
                        }
                    }
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                sh 'helm upgrade --install helep charts/helep -n helep --create-namespace --values charts/helep/values-dev.yaml'
            }
        }
    }

    post {
        success { echo 'Pipeline completed successfully!' }
        failure { echo 'Pipeline failed!' }
    }
}
