apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-data
  namespace: helep
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: helep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: carlos15976/helep-notification-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: KAFKA_BOOTSTRAP
          value: kafka:9092
        - name: DB_PATH
          value: /data/notification.db
        - name: SERVICE_PORT
          value: "8004"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: notification-data
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: helep
spec:
  selector:
    app: notification-service
  ports:
  - port: 8004
    targetPort: 8004
  type: ClusterIP
