apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sos-data
  namespace: helep
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sos-service
  namespace: helep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sos-service
  template:
    metadata:
      labels:
        app: sos-service
    spec:
      containers:
      - name: sos-service
        image: carlos15976/helep-sos-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: KAFKA_BOOTSTRAP
          value: kafka:9092
        - name: DB_PATH
          value: /data/sos.db
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: helep-secret
              key: JWT_SECRET
        - name: SERVICE_PORT
          value: "8002"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sos-data
---
apiVersion: v1
kind: Service
metadata:
  name: sos-service
  namespace: helep
spec:
  selector:
    app: sos-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
